[package]
name = "disc-v"
version = "0.1.2"
edition = "2024"
rust-version = "1.85.1"
authors = ["Christopher Swenson <swenson@swenson.io>"]
description = "A RISC-V disassembler"
license = "Apache-2.0"
repository = "https://github.com/swenson/disc-v"
readme = "README.md"
keywords = ["riscv", "risc-v", "disassembler", "decoder", "objdump"]
categories = ["development-tools", "no-std"]
include = ["/src", "/tests", "/scripts", "/README.md", "/CHANGELOG.md", "/LICENSE", "/NOTICE"]

