// Copyright (c) 2026 Christopher Swenson
// Licensed under the Apache-2.0 license.

//! The vector extension (V), and the vector bit-manipulation (Zvbb, Zvbc)
//! and cryptography (Zvkg, Zvkned, Zvknha/b, Zvksed, Zvksh) extensions.
//!
//! Generated by scripts/gen-vector-opcodes.py from riscv-opcodes 5783cf3bea312a48d28e3e2c8a2fcb55603e4bed
//! (Copyright (c) 2022 RISC-V International, BSD-3-Clause).

use super::Constraint::*;
use super::{Codec, MaskedOpcode, Opcode, Pseudo, masked};

pub(crate) static OP_V: [MaskedOpcode; 337] = [
    masked(
        0xc0007057,
        0xc000707f,
        Opcode::new("vsetivli", Codec::VsetIvli, "0,7,T"),
    ),
    masked(
        0x00007057,
        0x8000707f,
        Opcode::new("vsetvli", Codec::VsetVli, "0,1,T"),
    ),
    masked(
        0x80007057,
        0xfe00707f,
        Opcode::new("vsetvl", Codec::R, "0,1,2"),
    ),
    masked(
        0x00005057,
        0xfc00707f,
        Opcode::new("vfadd.vf", Codec::V, "D,B,4M"),
    ),
    masked(
        0x08005057,
        0xfc00707f,
        Opcode::new("vfsub.vf", Codec::V, "D,B,4M"),
    ),
    masked(
        0x10005057,
        0xfc00707f,
        Opcode::new("vfmin.vf", Codec::V, "D,B,4M"),
    ),
    masked(
        0x18005057,
        0xfc00707f,
        Opcode::new("vfmax.vf", Codec::V, "D,B,4M"),
    ),
    masked(
        0x20005057,
        0xfc00707f,
        Opcode::new("vfsgnj.vf", Codec::V, "D,B,4M"),
    ),
    masked(
        0x24005057,
        0xfc00707f,
        Opcode::new("vfsgnjn.vf", Codec::V, "D,B,4M"),
    ),
    masked(
        0x28005057,
        0xfc00707f,
        Opcode::new("vfsgnjx.vf", Codec::V, "D,B,4M"),
    ),
    masked(
        0x38005057,
        0xfc00707f,
        Opcode::new("vfslide1up.vf", Codec::V, "D,B,4M"),
    ),
    masked(
        0x3c005057,
        0xfc00707f,
        Opcode::new("vfslide1down.vf", Codec::V, "D,B,4M"),
    ),
    masked(
        0x42005057,
        0xfff0707f,
        Opcode::new("vfmv.s.f", Codec::V, "D,4"),
    ),
    masked(
        0x5c005057,
        0xfe00707f,
        Opcode::new("vfmerge.vfm", Codec::V, "D,B,4,Z"),
    ),
    masked(
        0x5e005057,
        0xfff0707f,
        Opcode::new("vfmv.v.f", Codec::V, "D,4"),
    ),
    masked(
        0x60005057,
        0xfc00707f,
        Opcode::new("vmfeq.vf", Codec::V, "D,B,4M"),
    ),
    masked(
        0x64005057,
        0xfc00707f,
        Opcode::new("vmfle.vf", Codec::V, "D,B,4M"),
    ),
    masked(
        0x6c005057,
        0xfc00707f,
        Opcode::new("vmflt.vf", Codec::V, "D,B,4M"),
    ),
    masked(
        0x70005057,
        0xfc00707f,
        Opcode::new("vmfne.vf", Codec::V, "D,B,4M"),
    ),
    masked(
        0x74005057,
        0xfc00707f,
        Opcode::new("vmfgt.vf", Codec::V, "D,B,4M"),
    ),
    masked(
        0x7c005057,
        0xfc00707f,
        Opcode::new("vmfge.vf", Codec::V, "D,B,4M"),
    ),
    masked(
        0x80005057,
        0xfc00707f,
        Opcode::new("vfdiv.vf", Codec::V, "D,B,4M"),
    ),
    masked(
        0x84005057,
        0xfc00707f,
        Opcode::new("vfrdiv.vf", Codec::V, "D,B,4M"),
    ),
    masked(
        0x90005057,
        0xfc00707f,
        Opcode::new("vfmul.vf", Codec::V, "D,B,4M"),
    ),
    masked(
        0x9c005057,
        0xfc00707f,
        Opcode::new("vfrsub.vf", Codec::V, "D,B,4M"),
    ),
    masked(
        0xa0005057,
        0xfc00707f,
        Opcode::new("vfmadd.vf", Codec::V, "D,4,BM"),
    ),
    masked(
        0xa4005057,
        0xfc00707f,
        Opcode::new("vfnmadd.vf", Codec::V, "D,4,BM"),
    ),
    masked(
        0xa8005057,
        0xfc00707f,
        Opcode::new("vfmsub.vf", Codec::V, "D,4,BM"),
    ),
    masked(
        0xac005057,
        0xfc00707f,
        Opcode::new("vfnmsub.vf", Codec::V, "D,4,BM"),
    ),
    masked(
        0xb0005057,
        0xfc00707f,
        Opcode::new("vfmacc.vf", Codec::V, "D,4,BM"),
    ),
    masked(
        0xb4005057,
        0xfc00707f,
        Opcode::new("vfnmacc.vf", Codec::V, "D,4,BM"),
    ),
    masked(
        0xb8005057,
        0xfc00707f,
        Opcode::new("vfmsac.vf", Codec::V, "D,4,BM"),
    ),
    masked(
        0xbc005057,
        0xfc00707f,
        Opcode::new("vfnmsac.vf", Codec::V, "D,4,BM"),
    ),
    masked(
        0xc0005057,
        0xfc00707f,
        Opcode::new("vfwadd.vf", Codec::V, "D,B,4M"),
    ),
    masked(
        0xc8005057,
        0xfc00707f,
        Opcode::new("vfwsub.vf", Codec::V, "D,B,4M"),
    ),
    masked(
        0xd0005057,
        0xfc00707f,
        Opcode::new("vfwadd.wf", Codec::V, "D,B,4M"),
    ),
    masked(
        0xd8005057,
        0xfc00707f,
        Opcode::new("vfwsub.wf", Codec::V, "D,B,4M"),
    ),
    masked(
        0xe0005057,
        0xfc00707f,
        Opcode::new("vfwmul.vf", Codec::V, "D,B,4M"),
    ),
    masked(
        0xf0005057,
        0xfc00707f,
        Opcode::new("vfwmacc.vf", Codec::V, "D,4,BM"),
    ),
    masked(
        0xf4005057,
        0xfc00707f,
        Opcode::new("vfwnmacc.vf", Codec::V, "D,4,BM"),
    ),
    masked(
        0xf8005057,
        0xfc00707f,
        Opcode::new("vfwmsac.vf", Codec::V, "D,4,BM"),
    ),
    masked(
        0xfc005057,
        0xfc00707f,
        Opcode::new("vfwnmsac.vf", Codec::V, "D,4,BM"),
    ),
    masked(
        0x00001057,
        0xfc00707f,
        Opcode::new("vfadd.vv", Codec::V, "D,B,AM"),
    ),
    masked(
        0x04001057,
        0xfc00707f,
        Opcode::new("vfredusum.vs", Codec::V, "D,B,AM"),
    ),
    masked(
        0x08001057,
        0xfc00707f,
        Opcode::new("vfsub.vv", Codec::V, "D,B,AM"),
    ),
    masked(
        0x0c001057,
        0xfc00707f,
        Opcode::new("vfredosum.vs", Codec::V, "D,B,AM"),
    ),
    masked(
        0x10001057,
        0xfc00707f,
        Opcode::new("vfmin.vv", Codec::V, "D,B,AM"),
    ),
    masked(
        0x14001057,
        0xfc00707f,
        Opcode::new("vfredmin.vs", Codec::V, "D,B,AM"),
    ),
    masked(
        0x18001057,
        0xfc00707f,
        Opcode::new("vfmax.vv", Codec::V, "D,B,AM"),
    ),
    masked(
        0x1c001057,
        0xfc00707f,
        Opcode::new("vfredmax.vs", Codec::V, "D,B,AM"),
    ),
    masked(
        0x20001057,
        0xfc00707f,
        Opcode::new("vfsgnj.vv", Codec::V, "D,B,AM"),
    ),
    masked(
        0x24001057,
        0xfc00707f,
        Opcode {
            pseudo: &[Pseudo::new(&VFNEG_V, &[Rs2EqRs1])],
            ..Opcode::new("vfsgnjn.vv", Codec::V, "D,B,AM")
        },
    ),
    masked(
        0x28001057,
        0xfc00707f,
        Opcode {
            pseudo: &[Pseudo::new(&VFABS_V, &[Rs2EqRs1])],
            ..Opcode::new("vfsgnjx.vv", Codec::V, "D,B,AM")
        },
    ),
    masked(
        0x42001057,
        0xfe0ff07f,
        Opcode::new("vfmv.f.s", Codec::V, "3,B"),
    ),
    masked(
        0x60001057,
        0xfc00707f,
        Opcode::new("vmfeq.vv", Codec::V, "D,B,AM"),
    ),
    masked(
        0x64001057,
        0xfc00707f,
        Opcode::new("vmfle.vv", Codec::V, "D,B,AM"),
    ),
    masked(
        0x6c001057,
        0xfc00707f,
        Opcode::new("vmflt.vv", Codec::V, "D,B,AM"),
    ),
    masked(
        0x70001057,
        0xfc00707f,
        Opcode::new("vmfne.vv", Codec::V, "D,B,AM"),
    ),
    masked(
        0x80001057,
        0xfc00707f,
        Opcode::new("vfdiv.vv", Codec::V, "D,B,AM"),
    ),
    masked(
        0x90001057,
        0xfc00707f,
        Opcode::new("vfmul.vv", Codec::V, "D,B,AM"),
    ),
    masked(
        0xa0001057,
        0xfc00707f,
        Opcode::new("vfmadd.vv", Codec::V, "D,A,BM"),
    ),
    masked(
        0xa4001057,
        0xfc00707f,
        Opcode::new("vfnmadd.vv", Codec::V, "D,A,BM"),
    ),
    masked(
        0xa8001057,
        0xfc00707f,
        Opcode::new("vfmsub.vv", Codec::V, "D,A,BM"),
    ),
    masked(
        0xac001057,
        0xfc00707f,
        Opcode::new("vfnmsub.vv", Codec::V, "D,A,BM"),
    ),
    masked(
        0xb0001057,
        0xfc00707f,
        Opcode::new("vfmacc.vv", Codec::V, "D,A,BM"),
    ),
    masked(
        0xb4001057,
        0xfc00707f,
        Opcode::new("vfnmacc.vv", Codec::V, "D,A,BM"),
    ),
    masked(
        0xb8001057,
        0xfc00707f,
        Opcode::new("vfmsac.vv", Codec::V, "D,A,BM"),
    ),
    masked(
        0xbc001057,
        0xfc00707f,
        Opcode::new("vfnmsac.vv", Codec::V, "D,A,BM"),
    ),
    masked(
        0x48001057,
        0xfc0ff07f,
        Opcode::new("vfcvt.xu.f.v", Codec::V, "D,BM"),
    ),
    masked(
        0x48009057,
        0xfc0ff07f,
        Opcode::new("vfcvt.x.f.v", Codec::V, "D,BM"),
    ),
    masked(
        0x48011057,
        0xfc0ff07f,
        Opcode::new("vfcvt.f.xu.v", Codec::V, "D,BM"),
    ),
    masked(
        0x48019057,
        0xfc0ff07f,
        Opcode::new("vfcvt.f.x.v", Codec::V, "D,BM"),
    ),
    masked(
        0x48031057,
        0xfc0ff07f,
        Opcode::new("vfcvt.rtz.xu.f.v", Codec::V, "D,BM"),
    ),
    masked(
        0x48039057,
        0xfc0ff07f,
        Opcode::new("vfcvt.rtz.x.f.v", Codec::V, "D,BM"),
    ),
    masked(
        0x48041057,
        0xfc0ff07f,
        Opcode::new("vfwcvt.xu.f.v", Codec::V, "D,BM"),
    ),
    masked(
        0x48049057,
        0xfc0ff07f,
        Opcode::new("vfwcvt.x.f.v", Codec::V, "D,BM"),
    ),
    masked(
        0x48051057,
        0xfc0ff07f,
        Opcode::new("vfwcvt.f.xu.v", Codec::V, "D,BM"),
    ),
    masked(
        0x48059057,
        0xfc0ff07f,
        Opcode::new("vfwcvt.f.x.v", Codec::V, "D,BM"),
    ),
    masked(
        0x48061057,
        0xfc0ff07f,
        Opcode::new("vfwcvt.f.f.v", Codec::V, "D,BM"),
    ),
    masked(
        0x48071057,
        0xfc0ff07f,
        Opcode::new("vfwcvt.rtz.xu.f.v", Codec::V, "D,BM"),
    ),
    masked(
        0x48079057,
        0xfc0ff07f,
        Opcode::new("vfwcvt.rtz.x.f.v", Codec::V, "D,BM"),
    ),
    masked(
        0x48081057,
        0xfc0ff07f,
        Opcode::new("vfncvt.xu.f.w", Codec::V, "D,BM"),
    ),
    masked(
        0x48089057,
        0xfc0ff07f,
        Opcode::new("vfncvt.x.f.w", Codec::V, "D,BM"),
    ),
    masked(
        0x48091057,
        0xfc0ff07f,
        Opcode::new("vfncvt.f.xu.w", Codec::V, "D,BM"),
    ),
    masked(
        0x48099057,
        0xfc0ff07f,
        Opcode::new("vfncvt.f.x.w", Codec::V, "D,BM"),
    ),
    masked(
        0x480a1057,
        0xfc0ff07f,
        Opcode::new("vfncvt.f.f.w", Codec::V, "D,BM"),
    ),
    masked(
        0x480a9057,
        0xfc0ff07f,
        Opcode::new("vfncvt.rod.f.f.w", Codec::V, "D,BM"),
    ),
    masked(
        0x480b1057,
        0xfc0ff07f,
        Opcode::new("vfncvt.rtz.xu.f.w", Codec::V, "D,BM"),
    ),
    masked(
        0x480b9057,
        0xfc0ff07f,
        Opcode::new("vfncvt.rtz.x.f.w", Codec::V, "D,BM"),
    ),
    masked(
        0x4c001057,
        0xfc0ff07f,
        Opcode::new("vfsqrt.v", Codec::V, "D,BM"),
    ),
    masked(
        0x4c021057,
        0xfc0ff07f,
        Opcode::new("vfrsqrt7.v", Codec::V, "D,BM"),
    ),
    masked(
        0x4c029057,
        0xfc0ff07f,
        Opcode::new("vfrec7.v", Codec::V, "D,BM"),
    ),
    masked(
        0x4c081057,
        0xfc0ff07f,
        Opcode::new("vfclass.v", Codec::V, "D,BM"),
    ),
    masked(
        0xc0001057,
        0xfc00707f,
        Opcode::new("vfwadd.vv", Codec::V, "D,B,AM"),
    ),
    masked(
        0xc4001057,
        0xfc00707f,
        Opcode::new("vfwredusum.vs", Codec::V, "D,B,AM"),
    ),
    masked(
        0xc8001057,
        0xfc00707f,
        Opcode::new("vfwsub.vv", Codec::V, "D,B,AM"),
    ),
    masked(
        0xcc001057,
        0xfc00707f,
        Opcode::new("vfwredosum.vs", Codec::V, "D,B,AM"),
    ),
    masked(
        0xd0001057,
        0xfc00707f,
        Opcode::new("vfwadd.wv", Codec::V, "D,B,AM"),
    ),
    masked(
        0xd8001057,
        0xfc00707f,
        Opcode::new("vfwsub.wv", Codec::V, "D,B,AM"),
    ),
    masked(
        0xe0001057,
        0xfc00707f,
        Opcode::new("vfwmul.vv", Codec::V, "D,B,AM"),
    ),
    masked(
        0xf0001057,
        0xfc00707f,
        Opcode::new("vfwmacc.vv", Codec::V, "D,A,BM"),
    ),
    masked(
        0xf4001057,
        0xfc00707f,
        Opcode::new("vfwnmacc.vv", Codec::V, "D,A,BM"),
    ),
    masked(
        0xf8001057,
        0xfc00707f,
        Opcode::new("vfwmsac.vv", Codec::V, "D,A,BM"),
    ),
    masked(
        0xfc001057,
        0xfc00707f,
        Opcode::new("vfwnmsac.vv", Codec::V, "D,A,BM"),
    ),
    masked(
        0x00004057,
        0xfc00707f,
        Opcode::new("vadd.vx", Codec::V, "D,B,1M"),
    ),
    masked(
        0x08004057,
        0xfc00707f,
        Opcode::new("vsub.vx", Codec::V, "D,B,1M"),
    ),
    masked(
        0x0c004057,
        0xfc00707f,
        Opcode {
            pseudo: &[Pseudo::new(&VNEG_V, &[Rs1Eq(0)])],
            ..Opcode::new("vrsub.vx", Codec::V, "D,B,1M")
        },
    ),
    masked(
        0x10004057,
        0xfc00707f,
        Opcode::new("vminu.vx", Codec::V, "D,B,1M"),
    ),
    masked(
        0x14004057,
        0xfc00707f,
        Opcode::new("vmin.vx", Codec::V, "D,B,1M"),
    ),
    masked(
        0x18004057,
        0xfc00707f,
        Opcode::new("vmaxu.vx", Codec::V, "D,B,1M"),
    ),
    masked(
        0x1c004057,
        0xfc00707f,
        Opcode::new("vmax.vx", Codec::V, "D,B,1M"),
    ),
    masked(
        0x24004057,
        0xfc00707f,
        Opcode::new("vand.vx", Codec::V, "D,B,1M"),
    ),
    masked(
        0x28004057,
        0xfc00707f,
        Opcode::new("vor.vx", Codec::V, "D,B,1M"),
    ),
    masked(
        0x2c004057,
        0xfc00707f,
        Opcode::new("vxor.vx", Codec::V, "D,B,1M"),
    ),
    masked(
        0x30004057,
        0xfc00707f,
        Opcode::new("vrgather.vx", Codec::V, "D,B,1M"),
    ),
    masked(
        0x38004057,
        0xfc00707f,
        Opcode::new("vslideup.vx", Codec::V, "D,B,1M"),
    ),
    masked(
        0x3c004057,
        0xfc00707f,
        Opcode::new("vslidedown.vx", Codec::V, "D,B,1M"),
    ),
    masked(
        0x40004057,
        0xfe00707f,
        Opcode::new("vadc.vxm", Codec::V, "D,B,1,Z"),
    ),
    masked(
        0x44004057,
        0xfe00707f,
        Opcode::new("vmadc.vxm", Codec::V, "D,B,1,Z"),
    ),
    masked(
        0x46004057,
        0xfe00707f,
        Opcode::new("vmadc.vx", Codec::V, "D,B,1"),
    ),
    masked(
        0x48004057,
        0xfe00707f,
        Opcode::new("vsbc.vxm", Codec::V, "D,B,1,Z"),
    ),
    masked(
        0x4c004057,
        0xfe00707f,
        Opcode::new("vmsbc.vxm", Codec::V, "D,B,1,Z"),
    ),
    masked(
        0x4e004057,
        0xfe00707f,
        Opcode::new("vmsbc.vx", Codec::V, "D,B,1"),
    ),
    masked(
        0x5c004057,
        0xfe00707f,
        Opcode::new("vmerge.vxm", Codec::V, "D,B,1,Z"),
    ),
    masked(
        0x5e004057,
        0xfff0707f,
        Opcode::new("vmv.v.x", Codec::V, "D,1"),
    ),
    masked(
        0x60004057,
        0xfc00707f,
        Opcode::new("vmseq.vx", Codec::V, "D,B,1M"),
    ),
    masked(
        0x64004057,
        0xfc00707f,
        Opcode::new("vmsne.vx", Codec::V, "D,B,1M"),
    ),
    masked(
        0x68004057,
        0xfc00707f,
        Opcode::new("vmsltu.vx", Codec::V, "D,B,1M"),
    ),
    masked(
        0x6c004057,
        0xfc00707f,
        Opcode::new("vmslt.vx", Codec::V, "D,B,1M"),
    ),
    masked(
        0x70004057,
        0xfc00707f,
        Opcode::new("vmsleu.vx", Codec::V, "D,B,1M"),
    ),
    masked(
        0x74004057,
        0xfc00707f,
        Opcode::new("vmsle.vx", Codec::V, "D,B,1M"),
    ),
    masked(
        0x78004057,
        0xfc00707f,
        Opcode::new("vmsgtu.vx", Codec::V, "D,B,1M"),
    ),
    masked(
        0x7c004057,
        0xfc00707f,
        Opcode::new("vmsgt.vx", Codec::V, "D,B,1M"),
    ),
    masked(
        0x80004057,
        0xfc00707f,
        Opcode::new("vsaddu.vx", Codec::V, "D,B,1M"),
    ),
    masked(
        0x84004057,
        0xfc00707f,
        Opcode::new("vsadd.vx", Codec::V, "D,B,1M"),
    ),
    masked(
        0x88004057,
        0xfc00707f,
        Opcode::new("vssubu.vx", Codec::V, "D,B,1M"),
    ),
    masked(
        0x8c004057,
        0xfc00707f,
        Opcode::new("vssub.vx", Codec::V, "D,B,1M"),
    ),
    masked(
        0x94004057,
        0xfc00707f,
        Opcode::new("vsll.vx", Codec::V, "D,B,1M"),
    ),
    masked(
        0x9c004057,
        0xfc00707f,
        Opcode::new("vsmul.vx", Codec::V, "D,B,1M"),
    ),
    masked(
        0xa0004057,
        0xfc00707f,
        Opcode::new("vsrl.vx", Codec::V, "D,B,1M"),
    ),
    masked(
        0xa4004057,
        0xfc00707f,
        Opcode::new("vsra.vx", Codec::V, "D,B,1M"),
    ),
    masked(
        0xa8004057,
        0xfc00707f,
        Opcode::new("vssrl.vx", Codec::V, "D,B,1M"),
    ),
    masked(
        0xac004057,
        0xfc00707f,
        Opcode::new("vssra.vx", Codec::V, "D,B,1M"),
    ),
    masked(
        0xb0004057,
        0xfc00707f,
        Opcode {
            pseudo: &[Pseudo::new(&VNCVT_X_X_W, &[Rs1Eq(0)])],
            ..Opcode::new("vnsrl.wx", Codec::V, "D,B,1M")
        },
    ),
    masked(
        0xb4004057,
        0xfc00707f,
        Opcode::new("vnsra.wx", Codec::V, "D,B,1M"),
    ),
    masked(
        0xb8004057,
        0xfc00707f,
        Opcode::new("vnclipu.wx", Codec::V, "D,B,1M"),
    ),
    masked(
        0xbc004057,
        0xfc00707f,
        Opcode::new("vnclip.wx", Codec::V, "D,B,1M"),
    ),
    masked(
        0x00000057,
        0xfc00707f,
        Opcode::new("vadd.vv", Codec::V, "D,B,AM"),
    ),
    masked(
        0x08000057,
        0xfc00707f,
        Opcode::new("vsub.vv", Codec::V, "D,B,AM"),
    ),
    masked(
        0x10000057,
        0xfc00707f,
        Opcode::new("vminu.vv", Codec::V, "D,B,AM"),
    ),
    masked(
        0x14000057,
        0xfc00707f,
        Opcode::new("vmin.vv", Codec::V, "D,B,AM"),
    ),
    masked(
        0x18000057,
        0xfc00707f,
        Opcode::new("vmaxu.vv", Codec::V, "D,B,AM"),
    ),
    masked(
        0x1c000057,
        0xfc00707f,
        Opcode::new("vmax.vv", Codec::V, "D,B,AM"),
    ),
    masked(
        0x24000057,
        0xfc00707f,
        Opcode::new("vand.vv", Codec::V, "D,B,AM"),
    ),
    masked(
        0x28000057,
        0xfc00707f,
        Opcode::new("vor.vv", Codec::V, "D,B,AM"),
    ),
    masked(
        0x2c000057,
        0xfc00707f,
        Opcode::new("vxor.vv", Codec::V, "D,B,AM"),
    ),
    masked(
        0x30000057,
        0xfc00707f,
        Opcode::new("vrgather.vv", Codec::V, "D,B,AM"),
    ),
    masked(
        0x38000057,
        0xfc00707f,
        Opcode::new("vrgatherei16.vv", Codec::V, "D,B,AM"),
    ),
    masked(
        0x40000057,
        0xfe00707f,
        Opcode::new("vadc.vvm", Codec::V, "D,B,A,Z"),
    ),
    masked(
        0x44000057,
        0xfe00707f,
        Opcode::new("vmadc.vvm", Codec::V, "D,B,A,Z"),
    ),
    masked(
        0x46000057,
        0xfe00707f,
        Opcode::new("vmadc.vv", Codec::V, "D,B,A"),
    ),
    masked(
        0x48000057,
        0xfe00707f,
        Opcode::new("vsbc.vvm", Codec::V, "D,B,A,Z"),
    ),
    masked(
        0x4c000057,
        0xfe00707f,
        Opcode::new("vmsbc.vvm", Codec::V, "D,B,A,Z"),
    ),
    masked(
        0x4e000057,
        0xfe00707f,
        Opcode::new("vmsbc.vv", Codec::V, "D,B,A"),
    ),
    masked(
        0x5c000057,
        0xfe00707f,
        Opcode::new("vmerge.vvm", Codec::V, "D,B,A,Z"),
    ),
    masked(
        0x5e000057,
        0xfff0707f,
        Opcode::new("vmv.v.v", Codec::V, "D,A"),
    ),
    masked(
        0x60000057,
        0xfc00707f,
        Opcode::new("vmseq.vv", Codec::V, "D,B,AM"),
    ),
    masked(
        0x64000057,
        0xfc00707f,
        Opcode::new("vmsne.vv", Codec::V, "D,B,AM"),
    ),
    masked(
        0x68000057,
        0xfc00707f,
        Opcode::new("vmsltu.vv", Codec::V, "D,B,AM"),
    ),
    masked(
        0x6c000057,
        0xfc00707f,
        Opcode::new("vmslt.vv", Codec::V, "D,B,AM"),
    ),
    masked(
        0x70000057,
        0xfc00707f,
        Opcode::new("vmsleu.vv", Codec::V, "D,B,AM"),
    ),
    masked(
        0x74000057,
        0xfc00707f,
        Opcode::new("vmsle.vv", Codec::V, "D,B,AM"),
    ),
    masked(
        0x80000057,
        0xfc00707f,
        Opcode::new("vsaddu.vv", Codec::V, "D,B,AM"),
    ),
    masked(
        0x84000057,
        0xfc00707f,
        Opcode::new("vsadd.vv", Codec::V, "D,B,AM"),
    ),
    masked(
        0x88000057,
        0xfc00707f,
        Opcode::new("vssubu.vv", Codec::V, "D,B,AM"),
    ),
    masked(
        0x8c000057,
        0xfc00707f,
        Opcode::new("vssub.vv", Codec::V, "D,B,AM"),
    ),
    masked(
        0x94000057,
        0xfc00707f,
        Opcode::new("vsll.vv", Codec::V, "D,B,AM"),
    ),
    masked(
        0x9c000057,
        0xfc00707f,
        Opcode::new("vsmul.vv", Codec::V, "D,B,AM"),
    ),
    masked(
        0xa0000057,
        0xfc00707f,
        Opcode::new("vsrl.vv", Codec::V, "D,B,AM"),
    ),
    masked(
        0xa4000057,
        0xfc00707f,
        Opcode::new("vsra.vv", Codec::V, "D,B,AM"),
    ),
    masked(
        0xa8000057,
        0xfc00707f,
        Opcode::new("vssrl.vv", Codec::V, "D,B,AM"),
    ),
    masked(
        0xac000057,
        0xfc00707f,
        Opcode::new("vssra.vv", Codec::V, "D,B,AM"),
    ),
    masked(
        0xb0000057,
        0xfc00707f,
        Opcode::new("vnsrl.wv", Codec::V, "D,B,AM"),
    ),
    masked(
        0xb4000057,
        0xfc00707f,
        Opcode::new("vnsra.wv", Codec::V, "D,B,AM"),
    ),
    masked(
        0xb8000057,
        0xfc00707f,
        Opcode::new("vnclipu.wv", Codec::V, "D,B,AM"),
    ),
    masked(
        0xbc000057,
        0xfc00707f,
        Opcode::new("vnclip.wv", Codec::V, "D,B,AM"),
    ),
    masked(
        0xc0000057,
        0xfc00707f,
        Opcode::new("vwredsumu.vs", Codec::V, "D,B,AM"),
    ),
    masked(
        0xc4000057,
        0xfc00707f,
        Opcode::new("vwredsum.vs", Codec::V, "D,B,AM"),
    ),
    masked(
        0x00003057,
        0xfc00707f,
        Opcode::new("vadd.vi", Codec::V, "D,B,iM"),
    ),
    masked(
        0x0c003057,
        0xfc00707f,
        Opcode::new("vrsub.vi", Codec::V, "D,B,iM"),
    ),
    masked(
        0x24003057,
        0xfc00707f,
        Opcode::new("vand.vi", Codec::V, "D,B,iM"),
    ),
    masked(
        0x28003057,
        0xfc00707f,
        Opcode::new("vor.vi", Codec::V, "D,B,iM"),
    ),
    masked(
        0x2c003057,
        0xfc00707f,
        Opcode {
            pseudo: &[Pseudo::new(&VNOT_V, &[ImmEq(-1)])],
            ..Opcode::new("vxor.vi", Codec::V, "D,B,iM")
        },
    ),
    masked(
        0x30003057,
        0xfc00707f,
        Opcode::new("vrgather.vi", Codec::Vu, "D,B,iM"),
    ),
    masked(
        0x38003057,
        0xfc00707f,
        Opcode::new("vslideup.vi", Codec::Vu, "D,B,iM"),
    ),
    masked(
        0x3c003057,
        0xfc00707f,
        Opcode::new("vslidedown.vi", Codec::Vu, "D,B,iM"),
    ),
    masked(
        0x40003057,
        0xfe00707f,
        Opcode::new("vadc.vim", Codec::V, "D,B,i,Z"),
    ),
    masked(
        0x44003057,
        0xfe00707f,
        Opcode::new("vmadc.vim", Codec::V, "D,B,i,Z"),
    ),
    masked(
        0x46003057,
        0xfe00707f,
        Opcode::new("vmadc.vi", Codec::V, "D,B,i"),
    ),
    masked(
        0x5c003057,
        0xfe00707f,
        Opcode::new("vmerge.vim", Codec::V, "D,B,i,Z"),
    ),
    masked(
        0x5e003057,
        0xfff0707f,
        Opcode::new("vmv.v.i", Codec::V, "D,i"),
    ),
    masked(
        0x60003057,
        0xfc00707f,
        Opcode::new("vmseq.vi", Codec::V, "D,B,iM"),
    ),
    masked(
        0x64003057,
        0xfc00707f,
        Opcode::new("vmsne.vi", Codec::V, "D,B,iM"),
    ),
    masked(
        0x70003057,
        0xfc00707f,
        Opcode::new("vmsleu.vi", Codec::V, "D,B,iM"),
    ),
    masked(
        0x74003057,
        0xfc00707f,
        Opcode::new("vmsle.vi", Codec::V, "D,B,iM"),
    ),
    masked(
        0x78003057,
        0xfc00707f,
        Opcode::new("vmsgtu.vi", Codec::V, "D,B,iM"),
    ),
    masked(
        0x7c003057,
        0xfc00707f,
        Opcode::new("vmsgt.vi", Codec::V, "D,B,iM"),
    ),
    masked(
        0x80003057,
        0xfc00707f,
        Opcode::new("vsaddu.vi", Codec::V, "D,B,iM"),
    ),
    masked(
        0x84003057,
        0xfc00707f,
        Opcode::new("vsadd.vi", Codec::V, "D,B,iM"),
    ),
    masked(
        0x94003057,
        0xfc00707f,
        Opcode::new("vsll.vi", Codec::Vu, "D,B,iM"),
    ),
    masked(
        0x9e003057,
        0xfe0ff07f,
        Opcode::new("vmv1r.v", Codec::V, "D,B"),
    ),
    masked(
        0x9e00b057,
        0xfe0ff07f,
        Opcode::new("vmv2r.v", Codec::V, "D,B"),
    ),
    masked(
        0x9e01b057,
        0xfe0ff07f,
        Opcode::new("vmv4r.v", Codec::V, "D,B"),
    ),
    masked(
        0x9e03b057,
        0xfe0ff07f,
        Opcode::new("vmv8r.v", Codec::V, "D,B"),
    ),
    masked(
        0xa0003057,
        0xfc00707f,
        Opcode::new("vsrl.vi", Codec::Vu, "D,B,iM"),
    ),
    masked(
        0xa4003057,
        0xfc00707f,
        Opcode::new("vsra.vi", Codec::Vu, "D,B,iM"),
    ),
    masked(
        0xa8003057,
        0xfc00707f,
        Opcode::new("vssrl.vi", Codec::Vu, "D,B,iM"),
    ),
    masked(
        0xac003057,
        0xfc00707f,
        Opcode::new("vssra.vi", Codec::Vu, "D,B,iM"),
    ),
    masked(
        0xb0003057,
        0xfc00707f,
        Opcode::new("vnsrl.wi", Codec::Vu, "D,B,iM"),
    ),
    masked(
        0xb4003057,
        0xfc00707f,
        Opcode::new("vnsra.wi", Codec::Vu, "D,B,iM"),
    ),
    masked(
        0xb8003057,
        0xfc00707f,
        Opcode::new("vnclipu.wi", Codec::Vu, "D,B,iM"),
    ),
    masked(
        0xbc003057,
        0xfc00707f,
        Opcode::new("vnclip.wi", Codec::Vu, "D,B,iM"),
    ),
    masked(
        0x00002057,
        0xfc00707f,
        Opcode::new("vredsum.vs", Codec::V, "D,B,AM"),
    ),
    masked(
        0x04002057,
        0xfc00707f,
        Opcode::new("vredand.vs", Codec::V, "D,B,AM"),
    ),
    masked(
        0x08002057,
        0xfc00707f,
        Opcode::new("vredor.vs", Codec::V, "D,B,AM"),
    ),
    masked(
        0x0c002057,
        0xfc00707f,
        Opcode::new("vredxor.vs", Codec::V, "D,B,AM"),
    ),
    masked(
        0x10002057,
        0xfc00707f,
        Opcode::new("vredminu.vs", Codec::V, "D,B,AM"),
    ),
    masked(
        0x14002057,
        0xfc00707f,
        Opcode::new("vredmin.vs", Codec::V, "D,B,AM"),
    ),
    masked(
        0x18002057,
        0xfc00707f,
        Opcode::new("vredmaxu.vs", Codec::V, "D,B,AM"),
    ),
    masked(
        0x1c002057,
        0xfc00707f,
        Opcode::new("vredmax.vs", Codec::V, "D,B,AM"),
    ),
    masked(
        0x20002057,
        0xfc00707f,
        Opcode::new("vaaddu.vv", Codec::V, "D,B,AM"),
    ),
    masked(
        0x24002057,
        0xfc00707f,
        Opcode::new("vaadd.vv", Codec::V, "D,B,AM"),
    ),
    masked(
        0x28002057,
        0xfc00707f,
        Opcode::new("vasubu.vv", Codec::V, "D,B,AM"),
    ),
    masked(
        0x2c002057,
        0xfc00707f,
        Opcode::new("vasub.vv", Codec::V, "D,B,AM"),
    ),
    masked(
        0x42002057,
        0xfe0ff07f,
        Opcode::new("vmv.x.s", Codec::V, "0,B"),
    ),
    masked(
        0x48012057,
        0xfc0ff07f,
        Opcode::new("vzext.vf8", Codec::V, "D,BM"),
    ),
    masked(
        0x4801a057,
        0xfc0ff07f,
        Opcode::new("vsext.vf8", Codec::V, "D,BM"),
    ),
    masked(
        0x48022057,
        0xfc0ff07f,
        Opcode::new("vzext.vf4", Codec::V, "D,BM"),
    ),
    masked(
        0x4802a057,
        0xfc0ff07f,
        Opcode::new("vsext.vf4", Codec::V, "D,BM"),
    ),
    masked(
        0x48032057,
        0xfc0ff07f,
        Opcode::new("vzext.vf2", Codec::V, "D,BM"),
    ),
    masked(
        0x4803a057,
        0xfc0ff07f,
        Opcode::new("vsext.vf2", Codec::V, "D,BM"),
    ),
    masked(
        0x5e002057,
        0xfe00707f,
        Opcode::new("vcompress.vm", Codec::V, "D,B,A"),
    ),
    masked(
        0x62002057,
        0xfe00707f,
        Opcode::new("vmandn.mm", Codec::V, "D,B,A"),
    ),
    masked(
        0x66002057,
        0xfe00707f,
        Opcode {
            pseudo: &[Pseudo::new(&VMMV_M, &[Rs2EqRs1])],
            ..Opcode::new("vmand.mm", Codec::V, "D,B,A")
        },
    ),
    masked(
        0x6a002057,
        0xfe00707f,
        Opcode::new("vmor.mm", Codec::V, "D,B,A"),
    ),
    masked(
        0x6e002057,
        0xfe00707f,
        Opcode {
            pseudo: &[Pseudo::new(&VMCLR_M, &[Rs2EqRs1, RdEqRs1])],
            ..Opcode::new("vmxor.mm", Codec::V, "D,B,A")
        },
    ),
    masked(
        0x72002057,
        0xfe00707f,
        Opcode::new("vmorn.mm", Codec::V, "D,B,A"),
    ),
    masked(
        0x76002057,
        0xfe00707f,
        Opcode {
            pseudo: &[Pseudo::new(&VMNOT_M, &[Rs2EqRs1])],
            ..Opcode::new("vmnand.mm", Codec::V, "D,B,A")
        },
    ),
    masked(
        0x7a002057,
        0xfe00707f,
        Opcode::new("vmnor.mm", Codec::V, "D,B,A"),
    ),
    masked(
        0x7e002057,
        0xfe00707f,
        Opcode {
            pseudo: &[Pseudo::new(&VMSET_M, &[Rs2EqRs1, RdEqRs1])],
            ..Opcode::new("vmxnor.mm", Codec::V, "D,B,A")
        },
    ),
    masked(
        0x5000a057,
        0xfc0ff07f,
        Opcode::new("vmsbf.m", Codec::V, "D,BM"),
    ),
    masked(
        0x50012057,
        0xfc0ff07f,
        Opcode::new("vmsof.m", Codec::V, "D,BM"),
    ),
    masked(
        0x5001a057,
        0xfc0ff07f,
        Opcode::new("vmsif.m", Codec::V, "D,BM"),
    ),
    masked(
        0x50082057,
        0xfc0ff07f,
        Opcode::new("viota.m", Codec::V, "D,BM"),
    ),
    masked(0x5008a057, 0xfdfff07f, Opcode::new("vid.v", Codec::V, "DM")),
    masked(
        0x40082057,
        0xfc0ff07f,
        Opcode::new("vcpop.m", Codec::V, "0,BM"),
    ),
    masked(
        0x4008a057,
        0xfc0ff07f,
        Opcode::new("vfirst.m", Codec::V, "0,BM"),
    ),
    masked(
        0x80002057,
        0xfc00707f,
        Opcode::new("vdivu.vv", Codec::V, "D,B,AM"),
    ),
    masked(
        0x84002057,
        0xfc00707f,
        Opcode::new("vdiv.vv", Codec::V, "D,B,AM"),
    ),
    masked(
        0x88002057,
        0xfc00707f,
        Opcode::new("vremu.vv", Codec::V, "D,B,AM"),
    ),
    masked(
        0x8c002057,
        0xfc00707f,
        Opcode::new("vrem.vv", Codec::V, "D,B,AM"),
    ),
    masked(
        0x90002057,
        0xfc00707f,
        Opcode::new("vmulhu.vv", Codec::V, "D,B,AM"),
    ),
    masked(
        0x94002057,
        0xfc00707f,
        Opcode::new("vmul.vv", Codec::V, "D,B,AM"),
    ),
    masked(
        0x98002057,
        0xfc00707f,
        Opcode::new("vmulhsu.vv", Codec::V, "D,B,AM"),
    ),
    masked(
        0x9c002057,
        0xfc00707f,
        Opcode::new("vmulh.vv", Codec::V, "D,B,AM"),
    ),
    masked(
        0xa4002057,
        0xfc00707f,
        Opcode::new("vmadd.vv", Codec::V, "D,A,BM"),
    ),
    masked(
        0xac002057,
        0xfc00707f,
        Opcode::new("vnmsub.vv", Codec::V, "D,A,BM"),
    ),
    masked(
        0xb4002057,
        0xfc00707f,
        Opcode::new("vmacc.vv", Codec::V, "D,A,BM"),
    ),
    masked(
        0xbc002057,
        0xfc00707f,
        Opcode::new("vnmsac.vv", Codec::V, "D,A,BM"),
    ),
    masked(
        0xc0002057,
        0xfc00707f,
        Opcode::new("vwaddu.vv", Codec::V, "D,B,AM"),
    ),
    masked(
        0xc4002057,
        0xfc00707f,
        Opcode::new("vwadd.vv", Codec::V, "D,B,AM"),
    ),
    masked(
        0xc8002057,
        0xfc00707f,
        Opcode::new("vwsubu.vv", Codec::V, "D,B,AM"),
    ),
    masked(
        0xcc002057,
        0xfc00707f,
        Opcode::new("vwsub.vv", Codec::V, "D,B,AM"),
    ),
    masked(
        0xd0002057,
        0xfc00707f,
        Opcode::new("vwaddu.wv", Codec::V, "D,B,AM"),
    ),
    masked(
        0xd4002057,
        0xfc00707f,
        Opcode::new("vwadd.wv", Codec::V, "D,B,AM"),
    ),
    masked(
        0xd8002057,
        0xfc00707f,
        Opcode::new("vwsubu.wv", Codec::V, "D,B,AM"),
    ),
    masked(
        0xdc002057,
        0xfc00707f,
        Opcode::new("vwsub.wv", Codec::V, "D,B,AM"),
    ),
    masked(
        0xe0002057,
        0xfc00707f,
        Opcode::new("vwmulu.vv", Codec::V, "D,B,AM"),
    ),
    masked(
        0xe8002057,
        0xfc00707f,
        Opcode::new("vwmulsu.vv", Codec::V, "D,B,AM"),
    ),
    masked(
        0xec002057,
        0xfc00707f,
        Opcode::new("vwmul.vv", Codec::V, "D,B,AM"),
    ),
    masked(
        0xf0002057,
        0xfc00707f,
        Opcode::new("vwmaccu.vv", Codec::V, "D,A,BM"),
    ),
    masked(
        0xf4002057,
        0xfc00707f,
        Opcode::new("vwmacc.vv", Codec::V, "D,A,BM"),
    ),
    masked(
        0xfc002057,
        0xfc00707f,
        Opcode::new("vwmaccsu.vv", Codec::V, "D,A,BM"),
    ),
    masked(
        0x20006057,
        0xfc00707f,
        Opcode::new("vaaddu.vx", Codec::V, "D,B,1M"),
    ),
    masked(
        0x24006057,
        0xfc00707f,
        Opcode::new("vaadd.vx", Codec::V, "D,B,1M"),
    ),
    masked(
        0x28006057,
        0xfc00707f,
        Opcode::new("vasubu.vx", Codec::V, "D,B,1M"),
    ),
    masked(
        0x2c006057,
        0xfc00707f,
        Opcode::new("vasub.vx", Codec::V, "D,B,1M"),
    ),
    masked(
        0x42006057,
        0xfff0707f,
        Opcode::new("vmv.s.x", Codec::V, "D,1"),
    ),
    masked(
        0x38006057,
        0xfc00707f,
        Opcode::new("vslide1up.vx", Codec::V, "D,B,1M"),
    ),
    masked(
        0x3c006057,
        0xfc00707f,
        Opcode::new("vslide1down.vx", Codec::V, "D,B,1M"),
    ),
    masked(
        0x80006057,
        0xfc00707f,
        Opcode::new("vdivu.vx", Codec::V, "D,B,1M"),
    ),
    masked(
        0x84006057,
        0xfc00707f,
        Opcode::new("vdiv.vx", Codec::V, "D,B,1M"),
    ),
    masked(
        0x88006057,
        0xfc00707f,
        Opcode::new("vremu.vx", Codec::V, "D,B,1M"),
    ),
    masked(
        0x8c006057,
        0xfc00707f,
        Opcode::new("vrem.vx", Codec::V, "D,B,1M"),
    ),
    masked(
        0x90006057,
        0xfc00707f,
        Opcode::new("vmulhu.vx", Codec::V, "D,B,1M"),
    ),
    masked(
        0x94006057,
        0xfc00707f,
        Opcode::new("vmul.vx", Codec::V, "D,B,1M"),
    ),
    masked(
        0x98006057,
        0xfc00707f,
        Opcode::new("vmulhsu.vx", Codec::V, "D,B,1M"),
    ),
    masked(
        0x9c006057,
        0xfc00707f,
        Opcode::new("vmulh.vx", Codec::V, "D,B,1M"),
    ),
    masked(
        0xa4006057,
        0xfc00707f,
        Opcode::new("vmadd.vx", Codec::V, "D,1,BM"),
    ),
    masked(
        0xac006057,
        0xfc00707f,
        Opcode::new("vnmsub.vx", Codec::V, "D,1,BM"),
    ),
    masked(
        0xb4006057,
        0xfc00707f,
        Opcode::new("vmacc.vx", Codec::V, "D,1,BM"),
    ),
    masked(
        0xbc006057,
        0xfc00707f,
        Opcode::new("vnmsac.vx", Codec::V, "D,1,BM"),
    ),
    masked(
        0xc0006057,
        0xfc00707f,
        Opcode {
            pseudo: &[Pseudo::new(&VWCVTU_X_X_V, &[Rs1Eq(0)])],
            ..Opcode::new("vwaddu.vx", Codec::V, "D,B,1M")
        },
    ),
    masked(
        0xc4006057,
        0xfc00707f,
        Opcode {
            pseudo: &[Pseudo::new(&VWCVT_X_X_V, &[Rs1Eq(0)])],
            ..Opcode::new("vwadd.vx", Codec::V, "D,B,1M")
        },
    ),
    masked(
        0xc8006057,
        0xfc00707f,
        Opcode::new("vwsubu.vx", Codec::V, "D,B,1M"),
    ),
    masked(
        0xcc006057,
        0xfc00707f,
        Opcode::new("vwsub.vx", Codec::V, "D,B,1M"),
    ),
    masked(
        0xd0006057,
        0xfc00707f,
        Opcode::new("vwaddu.wx", Codec::V, "D,B,1M"),
    ),
    masked(
        0xd4006057,
        0xfc00707f,
        Opcode::new("vwadd.wx", Codec::V, "D,B,1M"),
    ),
    masked(
        0xd8006057,
        0xfc00707f,
        Opcode::new("vwsubu.wx", Codec::V, "D,B,1M"),
    ),
    masked(
        0xdc006057,
        0xfc00707f,
        Opcode::new("vwsub.wx", Codec::V, "D,B,1M"),
    ),
    masked(
        0xe0006057,
        0xfc00707f,
        Opcode::new("vwmulu.vx", Codec::V, "D,B,1M"),
    ),
    masked(
        0xe8006057,
        0xfc00707f,
        Opcode::new("vwmulsu.vx", Codec::V, "D,B,1M"),
    ),
    masked(
        0xec006057,
        0xfc00707f,
        Opcode::new("vwmul.vx", Codec::V, "D,B,1M"),
    ),
    masked(
        0xf0006057,
        0xfc00707f,
        Opcode::new("vwmaccu.vx", Codec::V, "D,1,BM"),
    ),
    masked(
        0xf4006057,
        0xfc00707f,
        Opcode::new("vwmacc.vx", Codec::V, "D,1,BM"),
    ),
    masked(
        0xf8006057,
        0xfc00707f,
        Opcode::new("vwmaccus.vx", Codec::V, "D,1,BM"),
    ),
    masked(
        0xfc006057,
        0xfc00707f,
        Opcode::new("vwmaccsu.vx", Codec::V, "D,1,BM"),
    ),
    masked(
        0x04000057,
        0xfc00707f,
        Opcode::new("vandn.vv", Codec::V, "D,B,AM"),
    ),
    masked(
        0x04004057,
        0xfc00707f,
        Opcode::new("vandn.vx", Codec::V, "D,B,1M"),
    ),
    masked(
        0x48052057,
        0xfc0ff07f,
        Opcode::new("vbrev.v", Codec::V, "D,BM"),
    ),
    masked(
        0x48042057,
        0xfc0ff07f,
        Opcode::new("vbrev8.v", Codec::V, "D,BM"),
    ),
    masked(
        0x4804a057,
        0xfc0ff07f,
        Opcode::new("vrev8.v", Codec::V, "D,BM"),
    ),
    masked(
        0x48062057,
        0xfc0ff07f,
        Opcode::new("vclz.v", Codec::V, "D,BM"),
    ),
    masked(
        0x4806a057,
        0xfc0ff07f,
        Opcode::new("vctz.v", Codec::V, "D,BM"),
    ),
    masked(
        0x48072057,
        0xfc0ff07f,
        Opcode::new("vcpop.v", Codec::V, "D,BM"),
    ),
    masked(
        0x54000057,
        0xfc00707f,
        Opcode::new("vrol.vv", Codec::V, "D,B,AM"),
    ),
    masked(
        0x54004057,
        0xfc00707f,
        Opcode::new("vrol.vx", Codec::V, "D,B,1M"),
    ),
    masked(
        0x50000057,
        0xfc00707f,
        Opcode::new("vror.vv", Codec::V, "D,B,AM"),
    ),
    masked(
        0x50004057,
        0xfc00707f,
        Opcode::new("vror.vx", Codec::V, "D,B,1M"),
    ),
    masked(
        0x50003057,
        0xf800707f,
        Opcode::new("vror.vi", Codec::Vu6, "D,B,iM"),
    ),
    masked(
        0xd4000057,
        0xfc00707f,
        Opcode::new("vwsll.vv", Codec::V, "D,B,AM"),
    ),
    masked(
        0xd4004057,
        0xfc00707f,
        Opcode::new("vwsll.vx", Codec::V, "D,B,1M"),
    ),
    masked(
        0xd4003057,
        0xfc00707f,
        Opcode::new("vwsll.vi", Codec::Vu, "D,B,iM"),
    ),
    masked(
        0x30002057,
        0xfc00707f,
        Opcode::new("vclmul.vv", Codec::V, "D,B,AM"),
    ),
    masked(
        0x30006057,
        0xfc00707f,
        Opcode::new("vclmul.vx", Codec::V, "D,B,1M"),
    ),
    masked(
        0x34002057,
        0xfc00707f,
        Opcode::new("vclmulh.vv", Codec::V, "D,B,AM"),
    ),
    masked(
        0x34006057,
        0xfc00707f,
        Opcode::new("vclmulh.vx", Codec::V, "D,B,1M"),
    ),
];

pub(crate) static OP_VE: [MaskedOpcode; 21] = [
    masked(
        0xa208a077,
        0xfe0ff07f,
        Opcode::new("vgmul.vv", Codec::V, "D,B"),
    ),
    masked(
        0xb2002077,
        0xfe00707f,
        Opcode::new("vghsh.vv", Codec::V, "D,B,A"),
    ),
    masked(
        0xa200a077,
        0xfe0ff07f,
        Opcode::new("vaesdf.vv", Codec::V, "D,B"),
    ),
    masked(
        0xa600a077,
        0xfe0ff07f,
        Opcode::new("vaesdf.vs", Codec::V, "D,B"),
    ),
    masked(
        0xa2002077,
        0xfe0ff07f,
        Opcode::new("vaesdm.vv", Codec::V, "D,B"),
    ),
    masked(
        0xa6002077,
        0xfe0ff07f,
        Opcode::new("vaesdm.vs", Codec::V, "D,B"),
    ),
    masked(
        0xa201a077,
        0xfe0ff07f,
        Opcode::new("vaesef.vv", Codec::V, "D,B"),
    ),
    masked(
        0xa601a077,
        0xfe0ff07f,
        Opcode::new("vaesef.vs", Codec::V, "D,B"),
    ),
    masked(
        0xa2012077,
        0xfe0ff07f,
        Opcode::new("vaesem.vv", Codec::V, "D,B"),
    ),
    masked(
        0xa6012077,
        0xfe0ff07f,
        Opcode::new("vaesem.vs", Codec::V, "D,B"),
    ),
    masked(
        0xa603a077,
        0xfe0ff07f,
        Opcode::new("vaesz.vs", Codec::V, "D,B"),
    ),
    masked(
        0x8a002077,
        0xfe00707f,
        Opcode::new("vaeskf1.vi", Codec::Vu, "D,B,i"),
    ),
    masked(
        0xaa002077,
        0xfe00707f,
        Opcode::new("vaeskf2.vi", Codec::Vu, "D,B,i"),
    ),
    masked(
        0xb6002077,
        0xfe00707f,
        Opcode::new("vsha2ms.vv", Codec::V, "D,B,A"),
    ),
    masked(
        0xba002077,
        0xfe00707f,
        Opcode::new("vsha2ch.vv", Codec::V, "D,B,A"),
    ),
    masked(
        0xbe002077,
        0xfe00707f,
        Opcode::new("vsha2cl.vv", Codec::V, "D,B,A"),
    ),
    masked(
        0x86002077,
        0xfe00707f,
        Opcode::new("vsm4k.vi", Codec::Vu, "D,B,i"),
    ),
    masked(
        0xa2082077,
        0xfe0ff07f,
        Opcode::new("vsm4r.vv", Codec::V, "D,B"),
    ),
    masked(
        0xa6082077,
        0xfe0ff07f,
        Opcode::new("vsm4r.vs", Codec::V, "D,B"),
    ),
    masked(
        0xae002077,
        0xfe00707f,
        Opcode::new("vsm3c.vi", Codec::Vu, "D,B,i"),
    ),
    masked(
        0x82002077,
        0xfe00707f,
        Opcode::new("vsm3me.vv", Codec::V, "D,B,A"),
    ),
];

pub(crate) static LOAD_FP: [MaskedOpcode; 177] = [
    masked(
        0x02b00007,
        0xfff0707f,
        Opcode::new("vlm.v", Codec::V, "D,(1)"),
    ),
    masked(
        0x00000007,
        0xfdf0707f,
        Opcode::new("vle8.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0x20000007,
        0xfdf0707f,
        Opcode::new("vlseg2e8.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0x40000007,
        0xfdf0707f,
        Opcode::new("vlseg3e8.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0x60000007,
        0xfdf0707f,
        Opcode::new("vlseg4e8.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0x80000007,
        0xfdf0707f,
        Opcode::new("vlseg5e8.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0xa0000007,
        0xfdf0707f,
        Opcode::new("vlseg6e8.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0xc0000007,
        0xfdf0707f,
        Opcode::new("vlseg7e8.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0xe0000007,
        0xfdf0707f,
        Opcode::new("vlseg8e8.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0x00005007,
        0xfdf0707f,
        Opcode::new("vle16.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0x20005007,
        0xfdf0707f,
        Opcode::new("vlseg2e16.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0x40005007,
        0xfdf0707f,
        Opcode::new("vlseg3e16.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0x60005007,
        0xfdf0707f,
        Opcode::new("vlseg4e16.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0x80005007,
        0xfdf0707f,
        Opcode::new("vlseg5e16.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0xa0005007,
        0xfdf0707f,
        Opcode::new("vlseg6e16.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0xc0005007,
        0xfdf0707f,
        Opcode::new("vlseg7e16.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0xe0005007,
        0xfdf0707f,
        Opcode::new("vlseg8e16.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0x00006007,
        0xfdf0707f,
        Opcode::new("vle32.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0x20006007,
        0xfdf0707f,
        Opcode::new("vlseg2e32.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0x40006007,
        0xfdf0707f,
        Opcode::new("vlseg3e32.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0x60006007,
        0xfdf0707f,
        Opcode::new("vlseg4e32.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0x80006007,
        0xfdf0707f,
        Opcode::new("vlseg5e32.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0xa0006007,
        0xfdf0707f,
        Opcode::new("vlseg6e32.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0xc0006007,
        0xfdf0707f,
        Opcode::new("vlseg7e32.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0xe0006007,
        0xfdf0707f,
        Opcode::new("vlseg8e32.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0x00007007,
        0xfdf0707f,
        Opcode::new("vle64.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0x20007007,
        0xfdf0707f,
        Opcode::new("vlseg2e64.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0x40007007,
        0xfdf0707f,
        Opcode::new("vlseg3e64.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0x60007007,
        0xfdf0707f,
        Opcode::new("vlseg4e64.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0x80007007,
        0xfdf0707f,
        Opcode::new("vlseg5e64.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0xa0007007,
        0xfdf0707f,
        Opcode::new("vlseg6e64.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0xc0007007,
        0xfdf0707f,
        Opcode::new("vlseg7e64.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0xe0007007,
        0xfdf0707f,
        Opcode::new("vlseg8e64.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0x04000007,
        0xfc00707f,
        Opcode::new("vluxei8.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0x24000007,
        0xfc00707f,
        Opcode::new("vluxseg2ei8.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0x44000007,
        0xfc00707f,
        Opcode::new("vluxseg3ei8.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0x64000007,
        0xfc00707f,
        Opcode::new("vluxseg4ei8.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0x84000007,
        0xfc00707f,
        Opcode::new("vluxseg5ei8.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0xa4000007,
        0xfc00707f,
        Opcode::new("vluxseg6ei8.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0xc4000007,
        0xfc00707f,
        Opcode::new("vluxseg7ei8.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0xe4000007,
        0xfc00707f,
        Opcode::new("vluxseg8ei8.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0x04005007,
        0xfc00707f,
        Opcode::new("vluxei16.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0x24005007,
        0xfc00707f,
        Opcode::new("vluxseg2ei16.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0x44005007,
        0xfc00707f,
        Opcode::new("vluxseg3ei16.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0x64005007,
        0xfc00707f,
        Opcode::new("vluxseg4ei16.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0x84005007,
        0xfc00707f,
        Opcode::new("vluxseg5ei16.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0xa4005007,
        0xfc00707f,
        Opcode::new("vluxseg6ei16.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0xc4005007,
        0xfc00707f,
        Opcode::new("vluxseg7ei16.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0xe4005007,
        0xfc00707f,
        Opcode::new("vluxseg8ei16.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0x04006007,
        0xfc00707f,
        Opcode::new("vluxei32.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0x24006007,
        0xfc00707f,
        Opcode::new("vluxseg2ei32.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0x44006007,
        0xfc00707f,
        Opcode::new("vluxseg3ei32.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0x64006007,
        0xfc00707f,
        Opcode::new("vluxseg4ei32.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0x84006007,
        0xfc00707f,
        Opcode::new("vluxseg5ei32.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0xa4006007,
        0xfc00707f,
        Opcode::new("vluxseg6ei32.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0xc4006007,
        0xfc00707f,
        Opcode::new("vluxseg7ei32.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0xe4006007,
        0xfc00707f,
        Opcode::new("vluxseg8ei32.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0x04007007,
        0xfc00707f,
        Opcode::new("vluxei64.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0x24007007,
        0xfc00707f,
        Opcode::new("vluxseg2ei64.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0x44007007,
        0xfc00707f,
        Opcode::new("vluxseg3ei64.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0x64007007,
        0xfc00707f,
        Opcode::new("vluxseg4ei64.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0x84007007,
        0xfc00707f,
        Opcode::new("vluxseg5ei64.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0xa4007007,
        0xfc00707f,
        Opcode::new("vluxseg6ei64.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0xc4007007,
        0xfc00707f,
        Opcode::new("vluxseg7ei64.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0xe4007007,
        0xfc00707f,
        Opcode::new("vluxseg8ei64.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0x08000007,
        0xfc00707f,
        Opcode::new("vlse8.v", Codec::V, "D,(1),2M"),
    ),
    masked(
        0x28000007,
        0xfc00707f,
        Opcode::new("vlsseg2e8.v", Codec::V, "D,(1),2M"),
    ),
    masked(
        0x48000007,
        0xfc00707f,
        Opcode::new("vlsseg3e8.v", Codec::V, "D,(1),2M"),
    ),
    masked(
        0x68000007,
        0xfc00707f,
        Opcode::new("vlsseg4e8.v", Codec::V, "D,(1),2M"),
    ),
    masked(
        0x88000007,
        0xfc00707f,
        Opcode::new("vlsseg5e8.v", Codec::V, "D,(1),2M"),
    ),
    masked(
        0xa8000007,
        0xfc00707f,
        Opcode::new("vlsseg6e8.v", Codec::V, "D,(1),2M"),
    ),
    masked(
        0xc8000007,
        0xfc00707f,
        Opcode::new("vlsseg7e8.v", Codec::V, "D,(1),2M"),
    ),
    masked(
        0xe8000007,
        0xfc00707f,
        Opcode::new("vlsseg8e8.v", Codec::V, "D,(1),2M"),
    ),
    masked(
        0x08005007,
        0xfc00707f,
        Opcode::new("vlse16.v", Codec::V, "D,(1),2M"),
    ),
    masked(
        0x28005007,
        0xfc00707f,
        Opcode::new("vlsseg2e16.v", Codec::V, "D,(1),2M"),
    ),
    masked(
        0x48005007,
        0xfc00707f,
        Opcode::new("vlsseg3e16.v", Codec::V, "D,(1),2M"),
    ),
    masked(
        0x68005007,
        0xfc00707f,
        Opcode::new("vlsseg4e16.v", Codec::V, "D,(1),2M"),
    ),
    masked(
        0x88005007,
        0xfc00707f,
        Opcode::new("vlsseg5e16.v", Codec::V, "D,(1),2M"),
    ),
    masked(
        0xa8005007,
        0xfc00707f,
        Opcode::new("vlsseg6e16.v", Codec::V, "D,(1),2M"),
    ),
    masked(
        0xc8005007,
        0xfc00707f,
        Opcode::new("vlsseg7e16.v", Codec::V, "D,(1),2M"),
    ),
    masked(
        0xe8005007,
        0xfc00707f,
        Opcode::new("vlsseg8e16.v", Codec::V, "D,(1),2M"),
    ),
    masked(
        0x08006007,
        0xfc00707f,
        Opcode::new("vlse32.v", Codec::V, "D,(1),2M"),
    ),
    masked(
        0x28006007,
        0xfc00707f,
        Opcode::new("vlsseg2e32.v", Codec::V, "D,(1),2M"),
    ),
    masked(
        0x48006007,
        0xfc00707f,
        Opcode::new("vlsseg3e32.v", Codec::V, "D,(1),2M"),
    ),
    masked(
        0x68006007,
        0xfc00707f,
        Opcode::new("vlsseg4e32.v", Codec::V, "D,(1),2M"),
    ),
    masked(
        0x88006007,
        0xfc00707f,
        Opcode::new("vlsseg5e32.v", Codec::V, "D,(1),2M"),
    ),
    masked(
        0xa8006007,
        0xfc00707f,
        Opcode::new("vlsseg6e32.v", Codec::V, "D,(1),2M"),
    ),
    masked(
        0xc8006007,
        0xfc00707f,
        Opcode::new("vlsseg7e32.v", Codec::V, "D,(1),2M"),
    ),
    masked(
        0xe8006007,
        0xfc00707f,
        Opcode::new("vlsseg8e32.v", Codec::V, "D,(1),2M"),
    ),
    masked(
        0x08007007,
        0xfc00707f,
        Opcode::new("vlse64.v", Codec::V, "D,(1),2M"),
    ),
    masked(
        0x28007007,
        0xfc00707f,
        Opcode::new("vlsseg2e64.v", Codec::V, "D,(1),2M"),
    ),
    masked(
        0x48007007,
        0xfc00707f,
        Opcode::new("vlsseg3e64.v", Codec::V, "D,(1),2M"),
    ),
    masked(
        0x68007007,
        0xfc00707f,
        Opcode::new("vlsseg4e64.v", Codec::V, "D,(1),2M"),
    ),
    masked(
        0x88007007,
        0xfc00707f,
        Opcode::new("vlsseg5e64.v", Codec::V, "D,(1),2M"),
    ),
    masked(
        0xa8007007,
        0xfc00707f,
        Opcode::new("vlsseg6e64.v", Codec::V, "D,(1),2M"),
    ),
    masked(
        0xc8007007,
        0xfc00707f,
        Opcode::new("vlsseg7e64.v", Codec::V, "D,(1),2M"),
    ),
    masked(
        0xe8007007,
        0xfc00707f,
        Opcode::new("vlsseg8e64.v", Codec::V, "D,(1),2M"),
    ),
    masked(
        0x0c000007,
        0xfc00707f,
        Opcode::new("vloxei8.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0x2c000007,
        0xfc00707f,
        Opcode::new("vloxseg2ei8.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0x4c000007,
        0xfc00707f,
        Opcode::new("vloxseg3ei8.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0x6c000007,
        0xfc00707f,
        Opcode::new("vloxseg4ei8.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0x8c000007,
        0xfc00707f,
        Opcode::new("vloxseg5ei8.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0xac000007,
        0xfc00707f,
        Opcode::new("vloxseg6ei8.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0xcc000007,
        0xfc00707f,
        Opcode::new("vloxseg7ei8.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0xec000007,
        0xfc00707f,
        Opcode::new("vloxseg8ei8.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0x0c005007,
        0xfc00707f,
        Opcode::new("vloxei16.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0x2c005007,
        0xfc00707f,
        Opcode::new("vloxseg2ei16.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0x4c005007,
        0xfc00707f,
        Opcode::new("vloxseg3ei16.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0x6c005007,
        0xfc00707f,
        Opcode::new("vloxseg4ei16.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0x8c005007,
        0xfc00707f,
        Opcode::new("vloxseg5ei16.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0xac005007,
        0xfc00707f,
        Opcode::new("vloxseg6ei16.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0xcc005007,
        0xfc00707f,
        Opcode::new("vloxseg7ei16.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0xec005007,
        0xfc00707f,
        Opcode::new("vloxseg8ei16.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0x0c006007,
        0xfc00707f,
        Opcode::new("vloxei32.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0x2c006007,
        0xfc00707f,
        Opcode::new("vloxseg2ei32.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0x4c006007,
        0xfc00707f,
        Opcode::new("vloxseg3ei32.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0x6c006007,
        0xfc00707f,
        Opcode::new("vloxseg4ei32.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0x8c006007,
        0xfc00707f,
        Opcode::new("vloxseg5ei32.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0xac006007,
        0xfc00707f,
        Opcode::new("vloxseg6ei32.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0xcc006007,
        0xfc00707f,
        Opcode::new("vloxseg7ei32.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0xec006007,
        0xfc00707f,
        Opcode::new("vloxseg8ei32.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0x0c007007,
        0xfc00707f,
        Opcode::new("vloxei64.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0x2c007007,
        0xfc00707f,
        Opcode::new("vloxseg2ei64.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0x4c007007,
        0xfc00707f,
        Opcode::new("vloxseg3ei64.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0x6c007007,
        0xfc00707f,
        Opcode::new("vloxseg4ei64.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0x8c007007,
        0xfc00707f,
        Opcode::new("vloxseg5ei64.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0xac007007,
        0xfc00707f,
        Opcode::new("vloxseg6ei64.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0xcc007007,
        0xfc00707f,
        Opcode::new("vloxseg7ei64.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0xec007007,
        0xfc00707f,
        Opcode::new("vloxseg8ei64.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0x01000007,
        0xfdf0707f,
        Opcode::new("vle8ff.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0x21000007,
        0xfdf0707f,
        Opcode::new("vlseg2e8ff.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0x41000007,
        0xfdf0707f,
        Opcode::new("vlseg3e8ff.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0x61000007,
        0xfdf0707f,
        Opcode::new("vlseg4e8ff.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0x81000007,
        0xfdf0707f,
        Opcode::new("vlseg5e8ff.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0xa1000007,
        0xfdf0707f,
        Opcode::new("vlseg6e8ff.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0xc1000007,
        0xfdf0707f,
        Opcode::new("vlseg7e8ff.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0xe1000007,
        0xfdf0707f,
        Opcode::new("vlseg8e8ff.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0x01005007,
        0xfdf0707f,
        Opcode::new("vle16ff.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0x21005007,
        0xfdf0707f,
        Opcode::new("vlseg2e16ff.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0x41005007,
        0xfdf0707f,
        Opcode::new("vlseg3e16ff.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0x61005007,
        0xfdf0707f,
        Opcode::new("vlseg4e16ff.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0x81005007,
        0xfdf0707f,
        Opcode::new("vlseg5e16ff.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0xa1005007,
        0xfdf0707f,
        Opcode::new("vlseg6e16ff.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0xc1005007,
        0xfdf0707f,
        Opcode::new("vlseg7e16ff.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0xe1005007,
        0xfdf0707f,
        Opcode::new("vlseg8e16ff.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0x01006007,
        0xfdf0707f,
        Opcode::new("vle32ff.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0x21006007,
        0xfdf0707f,
        Opcode::new("vlseg2e32ff.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0x41006007,
        0xfdf0707f,
        Opcode::new("vlseg3e32ff.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0x61006007,
        0xfdf0707f,
        Opcode::new("vlseg4e32ff.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0x81006007,
        0xfdf0707f,
        Opcode::new("vlseg5e32ff.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0xa1006007,
        0xfdf0707f,
        Opcode::new("vlseg6e32ff.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0xc1006007,
        0xfdf0707f,
        Opcode::new("vlseg7e32ff.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0xe1006007,
        0xfdf0707f,
        Opcode::new("vlseg8e32ff.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0x01007007,
        0xfdf0707f,
        Opcode::new("vle64ff.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0x21007007,
        0xfdf0707f,
        Opcode::new("vlseg2e64ff.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0x41007007,
        0xfdf0707f,
        Opcode::new("vlseg3e64ff.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0x61007007,
        0xfdf0707f,
        Opcode::new("vlseg4e64ff.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0x81007007,
        0xfdf0707f,
        Opcode::new("vlseg5e64ff.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0xa1007007,
        0xfdf0707f,
        Opcode::new("vlseg6e64ff.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0xc1007007,
        0xfdf0707f,
        Opcode::new("vlseg7e64ff.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0xe1007007,
        0xfdf0707f,
        Opcode::new("vlseg8e64ff.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0x02800007,
        0xfff0707f,
        Opcode {
            pseudo: &[Pseudo::new(&VL1R_V, &[])],
            ..Opcode::new("vl1re8.v", Codec::V, "D,(1)")
        },
    ),
    masked(
        0x02805007,
        0xfff0707f,
        Opcode::new("vl1re16.v", Codec::V, "D,(1)"),
    ),
    masked(
        0x02806007,
        0xfff0707f,
        Opcode::new("vl1re32.v", Codec::V, "D,(1)"),
    ),
    masked(
        0x02807007,
        0xfff0707f,
        Opcode::new("vl1re64.v", Codec::V, "D,(1)"),
    ),
    masked(
        0x22800007,
        0xfff0707f,
        Opcode {
            pseudo: &[Pseudo::new(&VL2R_V, &[])],
            ..Opcode::new("vl2re8.v", Codec::V, "D,(1)")
        },
    ),
    masked(
        0x22805007,
        0xfff0707f,
        Opcode::new("vl2re16.v", Codec::V, "D,(1)"),
    ),
    masked(
        0x22806007,
        0xfff0707f,
        Opcode::new("vl2re32.v", Codec::V, "D,(1)"),
    ),
    masked(
        0x22807007,
        0xfff0707f,
        Opcode::new("vl2re64.v", Codec::V, "D,(1)"),
    ),
    masked(
        0x62800007,
        0xfff0707f,
        Opcode {
            pseudo: &[Pseudo::new(&VL4R_V, &[])],
            ..Opcode::new("vl4re8.v", Codec::V, "D,(1)")
        },
    ),
    masked(
        0x62805007,
        0xfff0707f,
        Opcode::new("vl4re16.v", Codec::V, "D,(1)"),
    ),
    masked(
        0x62806007,
        0xfff0707f,
        Opcode::new("vl4re32.v", Codec::V, "D,(1)"),
    ),
    masked(
        0x62807007,
        0xfff0707f,
        Opcode::new("vl4re64.v", Codec::V, "D,(1)"),
    ),
    masked(
        0xe2800007,
        0xfff0707f,
        Opcode {
            pseudo: &[Pseudo::new(&VL8R_V, &[])],
            ..Opcode::new("vl8re8.v", Codec::V, "D,(1)")
        },
    ),
    masked(
        0xe2805007,
        0xfff0707f,
        Opcode::new("vl8re16.v", Codec::V, "D,(1)"),
    ),
    masked(
        0xe2806007,
        0xfff0707f,
        Opcode::new("vl8re32.v", Codec::V, "D,(1)"),
    ),
    masked(
        0xe2807007,
        0xfff0707f,
        Opcode::new("vl8re64.v", Codec::V, "D,(1)"),
    ),
];

pub(crate) static STORE_FP: [MaskedOpcode; 133] = [
    masked(
        0x02b00027,
        0xfff0707f,
        Opcode::new("vsm.v", Codec::V, "D,(1)"),
    ),
    masked(
        0x00000027,
        0xfdf0707f,
        Opcode::new("vse8.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0x20000027,
        0xfdf0707f,
        Opcode::new("vsseg2e8.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0x40000027,
        0xfdf0707f,
        Opcode::new("vsseg3e8.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0x60000027,
        0xfdf0707f,
        Opcode::new("vsseg4e8.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0x80000027,
        0xfdf0707f,
        Opcode::new("vsseg5e8.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0xa0000027,
        0xfdf0707f,
        Opcode::new("vsseg6e8.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0xc0000027,
        0xfdf0707f,
        Opcode::new("vsseg7e8.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0xe0000027,
        0xfdf0707f,
        Opcode::new("vsseg8e8.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0x00005027,
        0xfdf0707f,
        Opcode::new("vse16.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0x20005027,
        0xfdf0707f,
        Opcode::new("vsseg2e16.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0x40005027,
        0xfdf0707f,
        Opcode::new("vsseg3e16.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0x60005027,
        0xfdf0707f,
        Opcode::new("vsseg4e16.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0x80005027,
        0xfdf0707f,
        Opcode::new("vsseg5e16.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0xa0005027,
        0xfdf0707f,
        Opcode::new("vsseg6e16.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0xc0005027,
        0xfdf0707f,
        Opcode::new("vsseg7e16.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0xe0005027,
        0xfdf0707f,
        Opcode::new("vsseg8e16.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0x00006027,
        0xfdf0707f,
        Opcode::new("vse32.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0x20006027,
        0xfdf0707f,
        Opcode::new("vsseg2e32.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0x40006027,
        0xfdf0707f,
        Opcode::new("vsseg3e32.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0x60006027,
        0xfdf0707f,
        Opcode::new("vsseg4e32.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0x80006027,
        0xfdf0707f,
        Opcode::new("vsseg5e32.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0xa0006027,
        0xfdf0707f,
        Opcode::new("vsseg6e32.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0xc0006027,
        0xfdf0707f,
        Opcode::new("vsseg7e32.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0xe0006027,
        0xfdf0707f,
        Opcode::new("vsseg8e32.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0x00007027,
        0xfdf0707f,
        Opcode::new("vse64.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0x20007027,
        0xfdf0707f,
        Opcode::new("vsseg2e64.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0x40007027,
        0xfdf0707f,
        Opcode::new("vsseg3e64.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0x60007027,
        0xfdf0707f,
        Opcode::new("vsseg4e64.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0x80007027,
        0xfdf0707f,
        Opcode::new("vsseg5e64.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0xa0007027,
        0xfdf0707f,
        Opcode::new("vsseg6e64.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0xc0007027,
        0xfdf0707f,
        Opcode::new("vsseg7e64.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0xe0007027,
        0xfdf0707f,
        Opcode::new("vsseg8e64.v", Codec::V, "D,(1)M"),
    ),
    masked(
        0x04000027,
        0xfc00707f,
        Opcode::new("vsuxei8.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0x24000027,
        0xfc00707f,
        Opcode::new("vsuxseg2ei8.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0x44000027,
        0xfc00707f,
        Opcode::new("vsuxseg3ei8.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0x64000027,
        0xfc00707f,
        Opcode::new("vsuxseg4ei8.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0x84000027,
        0xfc00707f,
        Opcode::new("vsuxseg5ei8.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0xa4000027,
        0xfc00707f,
        Opcode::new("vsuxseg6ei8.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0xc4000027,
        0xfc00707f,
        Opcode::new("vsuxseg7ei8.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0xe4000027,
        0xfc00707f,
        Opcode::new("vsuxseg8ei8.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0x04005027,
        0xfc00707f,
        Opcode::new("vsuxei16.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0x24005027,
        0xfc00707f,
        Opcode::new("vsuxseg2ei16.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0x44005027,
        0xfc00707f,
        Opcode::new("vsuxseg3ei16.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0x64005027,
        0xfc00707f,
        Opcode::new("vsuxseg4ei16.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0x84005027,
        0xfc00707f,
        Opcode::new("vsuxseg5ei16.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0xa4005027,
        0xfc00707f,
        Opcode::new("vsuxseg6ei16.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0xc4005027,
        0xfc00707f,
        Opcode::new("vsuxseg7ei16.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0xe4005027,
        0xfc00707f,
        Opcode::new("vsuxseg8ei16.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0x04006027,
        0xfc00707f,
        Opcode::new("vsuxei32.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0x24006027,
        0xfc00707f,
        Opcode::new("vsuxseg2ei32.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0x44006027,
        0xfc00707f,
        Opcode::new("vsuxseg3ei32.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0x64006027,
        0xfc00707f,
        Opcode::new("vsuxseg4ei32.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0x84006027,
        0xfc00707f,
        Opcode::new("vsuxseg5ei32.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0xa4006027,
        0xfc00707f,
        Opcode::new("vsuxseg6ei32.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0xc4006027,
        0xfc00707f,
        Opcode::new("vsuxseg7ei32.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0xe4006027,
        0xfc00707f,
        Opcode::new("vsuxseg8ei32.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0x04007027,
        0xfc00707f,
        Opcode::new("vsuxei64.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0x24007027,
        0xfc00707f,
        Opcode::new("vsuxseg2ei64.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0x44007027,
        0xfc00707f,
        Opcode::new("vsuxseg3ei64.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0x64007027,
        0xfc00707f,
        Opcode::new("vsuxseg4ei64.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0x84007027,
        0xfc00707f,
        Opcode::new("vsuxseg5ei64.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0xa4007027,
        0xfc00707f,
        Opcode::new("vsuxseg6ei64.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0xc4007027,
        0xfc00707f,
        Opcode::new("vsuxseg7ei64.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0xe4007027,
        0xfc00707f,
        Opcode::new("vsuxseg8ei64.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0x08000027,
        0xfc00707f,
        Opcode::new("vsse8.v", Codec::V, "D,(1),2M"),
    ),
    masked(
        0x28000027,
        0xfc00707f,
        Opcode::new("vssseg2e8.v", Codec::V, "D,(1),2M"),
    ),
    masked(
        0x48000027,
        0xfc00707f,
        Opcode::new("vssseg3e8.v", Codec::V, "D,(1),2M"),
    ),
    masked(
        0x68000027,
        0xfc00707f,
        Opcode::new("vssseg4e8.v", Codec::V, "D,(1),2M"),
    ),
    masked(
        0x88000027,
        0xfc00707f,
        Opcode::new("vssseg5e8.v", Codec::V, "D,(1),2M"),
    ),
    masked(
        0xa8000027,
        0xfc00707f,
        Opcode::new("vssseg6e8.v", Codec::V, "D,(1),2M"),
    ),
    masked(
        0xc8000027,
        0xfc00707f,
        Opcode::new("vssseg7e8.v", Codec::V, "D,(1),2M"),
    ),
    masked(
        0xe8000027,
        0xfc00707f,
        Opcode::new("vssseg8e8.v", Codec::V, "D,(1),2M"),
    ),
    masked(
        0x08005027,
        0xfc00707f,
        Opcode::new("vsse16.v", Codec::V, "D,(1),2M"),
    ),
    masked(
        0x28005027,
        0xfc00707f,
        Opcode::new("vssseg2e16.v", Codec::V, "D,(1),2M"),
    ),
    masked(
        0x48005027,
        0xfc00707f,
        Opcode::new("vssseg3e16.v", Codec::V, "D,(1),2M"),
    ),
    masked(
        0x68005027,
        0xfc00707f,
        Opcode::new("vssseg4e16.v", Codec::V, "D,(1),2M"),
    ),
    masked(
        0x88005027,
        0xfc00707f,
        Opcode::new("vssseg5e16.v", Codec::V, "D,(1),2M"),
    ),
    masked(
        0xa8005027,
        0xfc00707f,
        Opcode::new("vssseg6e16.v", Codec::V, "D,(1),2M"),
    ),
    masked(
        0xc8005027,
        0xfc00707f,
        Opcode::new("vssseg7e16.v", Codec::V, "D,(1),2M"),
    ),
    masked(
        0xe8005027,
        0xfc00707f,
        Opcode::new("vssseg8e16.v", Codec::V, "D,(1),2M"),
    ),
    masked(
        0x08006027,
        0xfc00707f,
        Opcode::new("vsse32.v", Codec::V, "D,(1),2M"),
    ),
    masked(
        0x28006027,
        0xfc00707f,
        Opcode::new("vssseg2e32.v", Codec::V, "D,(1),2M"),
    ),
    masked(
        0x48006027,
        0xfc00707f,
        Opcode::new("vssseg3e32.v", Codec::V, "D,(1),2M"),
    ),
    masked(
        0x68006027,
        0xfc00707f,
        Opcode::new("vssseg4e32.v", Codec::V, "D,(1),2M"),
    ),
    masked(
        0x88006027,
        0xfc00707f,
        Opcode::new("vssseg5e32.v", Codec::V, "D,(1),2M"),
    ),
    masked(
        0xa8006027,
        0xfc00707f,
        Opcode::new("vssseg6e32.v", Codec::V, "D,(1),2M"),
    ),
    masked(
        0xc8006027,
        0xfc00707f,
        Opcode::new("vssseg7e32.v", Codec::V, "D,(1),2M"),
    ),
    masked(
        0xe8006027,
        0xfc00707f,
        Opcode::new("vssseg8e32.v", Codec::V, "D,(1),2M"),
    ),
    masked(
        0x08007027,
        0xfc00707f,
        Opcode::new("vsse64.v", Codec::V, "D,(1),2M"),
    ),
    masked(
        0x28007027,
        0xfc00707f,
        Opcode::new("vssseg2e64.v", Codec::V, "D,(1),2M"),
    ),
    masked(
        0x48007027,
        0xfc00707f,
        Opcode::new("vssseg3e64.v", Codec::V, "D,(1),2M"),
    ),
    masked(
        0x68007027,
        0xfc00707f,
        Opcode::new("vssseg4e64.v", Codec::V, "D,(1),2M"),
    ),
    masked(
        0x88007027,
        0xfc00707f,
        Opcode::new("vssseg5e64.v", Codec::V, "D,(1),2M"),
    ),
    masked(
        0xa8007027,
        0xfc00707f,
        Opcode::new("vssseg6e64.v", Codec::V, "D,(1),2M"),
    ),
    masked(
        0xc8007027,
        0xfc00707f,
        Opcode::new("vssseg7e64.v", Codec::V, "D,(1),2M"),
    ),
    masked(
        0xe8007027,
        0xfc00707f,
        Opcode::new("vssseg8e64.v", Codec::V, "D,(1),2M"),
    ),
    masked(
        0x0c000027,
        0xfc00707f,
        Opcode::new("vsoxei8.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0x2c000027,
        0xfc00707f,
        Opcode::new("vsoxseg2ei8.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0x4c000027,
        0xfc00707f,
        Opcode::new("vsoxseg3ei8.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0x6c000027,
        0xfc00707f,
        Opcode::new("vsoxseg4ei8.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0x8c000027,
        0xfc00707f,
        Opcode::new("vsoxseg5ei8.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0xac000027,
        0xfc00707f,
        Opcode::new("vsoxseg6ei8.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0xcc000027,
        0xfc00707f,
        Opcode::new("vsoxseg7ei8.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0xec000027,
        0xfc00707f,
        Opcode::new("vsoxseg8ei8.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0x0c005027,
        0xfc00707f,
        Opcode::new("vsoxei16.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0x2c005027,
        0xfc00707f,
        Opcode::new("vsoxseg2ei16.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0x4c005027,
        0xfc00707f,
        Opcode::new("vsoxseg3ei16.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0x6c005027,
        0xfc00707f,
        Opcode::new("vsoxseg4ei16.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0x8c005027,
        0xfc00707f,
        Opcode::new("vsoxseg5ei16.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0xac005027,
        0xfc00707f,
        Opcode::new("vsoxseg6ei16.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0xcc005027,
        0xfc00707f,
        Opcode::new("vsoxseg7ei16.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0xec005027,
        0xfc00707f,
        Opcode::new("vsoxseg8ei16.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0x0c006027,
        0xfc00707f,
        Opcode::new("vsoxei32.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0x2c006027,
        0xfc00707f,
        Opcode::new("vsoxseg2ei32.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0x4c006027,
        0xfc00707f,
        Opcode::new("vsoxseg3ei32.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0x6c006027,
        0xfc00707f,
        Opcode::new("vsoxseg4ei32.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0x8c006027,
        0xfc00707f,
        Opcode::new("vsoxseg5ei32.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0xac006027,
        0xfc00707f,
        Opcode::new("vsoxseg6ei32.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0xcc006027,
        0xfc00707f,
        Opcode::new("vsoxseg7ei32.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0xec006027,
        0xfc00707f,
        Opcode::new("vsoxseg8ei32.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0x0c007027,
        0xfc00707f,
        Opcode::new("vsoxei64.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0x2c007027,
        0xfc00707f,
        Opcode::new("vsoxseg2ei64.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0x4c007027,
        0xfc00707f,
        Opcode::new("vsoxseg3ei64.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0x6c007027,
        0xfc00707f,
        Opcode::new("vsoxseg4ei64.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0x8c007027,
        0xfc00707f,
        Opcode::new("vsoxseg5ei64.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0xac007027,
        0xfc00707f,
        Opcode::new("vsoxseg6ei64.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0xcc007027,
        0xfc00707f,
        Opcode::new("vsoxseg7ei64.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0xec007027,
        0xfc00707f,
        Opcode::new("vsoxseg8ei64.v", Codec::V, "D,(1),BM"),
    ),
    masked(
        0x02800027,
        0xfff0707f,
        Opcode::new("vs1r.v", Codec::V, "D,(1)"),
    ),
    masked(
        0x22800027,
        0xfff0707f,
        Opcode::new("vs2r.v", Codec::V, "D,(1)"),
    ),
    masked(
        0x62800027,
        0xfff0707f,
        Opcode::new("vs4r.v", Codec::V, "D,(1)"),
    ),
    masked(
        0xe2800027,
        0xfff0707f,
        Opcode::new("vs8r.v", Codec::V, "D,(1)"),
    ),
];

static VNOT_V: Opcode = Opcode::new("vnot.v", Codec::V, "D,BM");
static VNEG_V: Opcode = Opcode::new("vneg.v", Codec::V, "D,BM");
static VWCVT_X_X_V: Opcode = Opcode::new("vwcvt.x.x.v", Codec::V, "D,BM");
static VWCVTU_X_X_V: Opcode = Opcode::new("vwcvtu.x.x.v", Codec::V, "D,BM");
static VNCVT_X_X_W: Opcode = Opcode::new("vncvt.x.x.w", Codec::V, "D,BM");
static VMMV_M: Opcode = Opcode::new("vmmv.m", Codec::V, "D,B");
static VMCLR_M: Opcode = Opcode::new("vmclr.m", Codec::V, "D");
static VMSET_M: Opcode = Opcode::new("vmset.m", Codec::V, "D");
static VMNOT_M: Opcode = Opcode::new("vmnot.m", Codec::V, "D,B");
static VFNEG_V: Opcode = Opcode::new("vfneg.v", Codec::V, "D,BM");
static VFABS_V: Opcode = Opcode::new("vfabs.v", Codec::V, "D,BM");
static VL1R_V: Opcode = Opcode::new("vl1r.v", Codec::V, "D,(1)");
static VL2R_V: Opcode = Opcode::new("vl2r.v", Codec::V, "D,(1)");
static VL4R_V: Opcode = Opcode::new("vl4r.v", Codec::V, "D,(1)");
static VL8R_V: Opcode = Opcode::new("vl8r.v", Codec::V, "D,(1)");
